// Generated by Wrangler by running `wrangler types`

interface Env {
	R2_ACCOUNT_ID: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
	R2_PUBLIC_BUCKET_URL: string;
	R2_BUCKET_NAME: string;
}
