// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	AUTH_SECRET: string;
	AUTH_URL: string;
	GITHUB_ID: string;
	GITHUB_SECRET: string;
	GOOGLE_ID: string;
	GOOGLE_SECRET: string;
	SECRETS_HOST: string;
	DB: D1Database;
	SECRETS_APP: Fetcher;
}
