// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	AUTH_SECRET: string;
	AUTH_URL: string;
	GITHUB_ID: string;
	GITHUB_SECRET: string;
	DB: D1Database;
}
